# Generated by Django 5.2.7 on 2025-11-13 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tên chương trình')),
                ('description', models.TextField(verbose_name='Mô tả')),
                ('discount_text', models.CharField(help_text='VD: Giảm 20%', max_length=50, verbose_name='Mức giảm')),
                ('image', models.ImageField(upload_to='promotions/')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
