# Generated by Django 5.2.7 on 2025-11-13 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_alter_booking_status'),
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='target_room_types',
            field=models.ManyToManyField(blank=True, related_name='promotions', to='booking.roomtype', verbose_name='Áp dụng cho loại phòng'),
        ),
    ]
