# Generated by Django 5.2.7 on 2025-11-14 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0002_promotion_target_room_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='discount_text',
            field=models.CharField(help_text='VD: Giảm 20%', max_length=100, verbose_name='Mức giảm'),
        ),
    ]
