# Generated by Django 5.2.7 on 2025-11-10 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='image',
        ),
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('DINING', 'Nhà hàng & Ăn uống'), ('WELLNESS', 'Spa & Sức khỏe'), ('RECREATION', 'Giải trí & Thể thao'), ('OTHER', 'Khác')], default='RECREATION', max_length=20),
        ),
        migrations.AddField(
            model_name='service',
            name='opening_hours',
            field=models.CharField(blank=True, help_text='VD: 09:00 - 22:00 (Hàng ngày)', max_length=100),
        ),
        migrations.AddField(
            model_name='service',
            name='rules',
            field=models.TextField(blank=True, help_text='Quy định sử dụng, yêu cầu trang phục, v.v.'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(help_text='Mô tả chi tiết về dịch vụ'),
        ),
        migrations.AlterField(
            model_name='service',
            name='price_info',
            field=models.CharField(help_text="VD: 'Miễn phí cho khách' hoặc 'Từ 500,000 VNĐ'", max_length=100),
        ),
        migrations.CreateModel(
            name='ServiceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='service_gallery/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('is_main', models.BooleanField(default=False, help_text='Đánh dấu nếu đây là ảnh đại diện chính')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='services.service')),
            ],
        ),
    ]
