# Generated by Django 5.2.7 on 2025-11-05 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_remove_roomtype_image_roomimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomimage',
            name='is_thumbnail',
            field=models.BooleanField(default=False, help_text='Đánh dấu nếu đây là ảnh đại diện cho loại phòng này.'),
        ),
    ]
