# Generated by Django 5.2.7 on 2025-11-07 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_roomimage_is_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('available_count', models.IntegerField(default=0)),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.roomtype')),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('room_type', 'date')},
            },
        ),
    ]
