# Generated by Django 5.2.7 on 2025-11-07 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_inventory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('booked', 'Xác nhận'), ('checked_in', 'Đã nhận phòng'), ('checked_out', 'Đã trả phòng'), ('canceled', 'Đã hủy')], default='booked', max_length=20),
        ),
    ]
