# Generated by Django 5.2.7 on 2025-11-19 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_alter_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('clean', 'Sạch - Sẵn sàng đón khách'), ('dirty', 'Bẩn - Cần dọn dẹp'), ('maintenance', 'Đang bảo trì/Sửa chữa'), ('occupied', 'Đang có khách ở')], default='clean', max_length=20, verbose_name='Trạng thái phòng'),
        ),
    ]
