"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-sol+u78_9@$xrg1lfbe01c-r3-25py$q9hiyi&pmyeqc8*nked'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

ALLAUTH_UI_THEME = "daisyui"

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'import_export',
    'django_extensions',
    'booking.apps.BookingConfig',
    'pages.apps.PagesConfig',
    'users.apps.UsersConfig',
    'chatbot.apps.ChatbotConfig',
    'services.apps.ServicesConfig',
    'marketing.apps.MarketingConfig',
    'blog.apps.BlogConfig',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google', 
]

SITE_ID = 1

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]


# Các thiết lập tùy chọn của allauth
ACCOUNT_LOGIN_METHODS = {'email'}
ACCOUNT_SIGNUP_FIELDS = ['email*', 'password1*', 'password2*']
ACCOUNT_EMAIL_VERIFICATION = 'none'  # Có thể là 'mandatory', 'optional', hoặc 'none'
SOCIALACCOUNT_LOGIN_ON_GET = True
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

ACCOUNT_LOGOUT_ON_PASSWORD_CHANGE = False

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# URL công khai để truy cập file static (VD: /static/css/styles.css)
STATIC_URL = 'static/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

STATIC_ROOT = BASE_DIR / 'static_collected'

LOGIN_URL = '/accounts/login/'

LOGIN_REDIRECT_URL = '/'  

LOGOUT_REDIRECT_URL = '/' 

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'users.User' 

SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': [
            'profile',
            'email',
            'https://www.googleapis.com/auth/gmail.readonly',
        ],
        'AUTH_PARAMS': {
          'access_type': 'offline',  # request refresh token
        }
    }
}
SOCIALACCOUNT_STORE_TOKENS = True

# 1. URL công khai để truy cập file media (VD: /media/services/spa.jpg)
MEDIA_URL = '/media/'

# 2. Đường dẫn tuyệt đối đến thư mục media trên ổ đĩa
MEDIA_ROOT = BASE_DIR / 'media'


# ------------- CÀI ĐẶT JAZZMIN -------------
JAZZMIN_SETTINGS = {
    # Tiêu đề trên tab trình duyệt (thay thế "Django site admin")
    "site_title": "The Sailing Bay Admin",

    # Tiêu đề ở góc trên bên trái (thay thế "Django administration")
    "site_header": "The Sailing Bay",

    # Tên thương hiệu (cho màn hình đăng nhập)
    "site_brand": "The Sailing Bay",

    # Logo cho màn hình đăng nhập (đặt logo của bạn vào static/images/)
    # "login_logo": "images/logo-login.png",

    # Logo cho thanh điều hướng
    # "site_logo": "images/logo-navbar.png",

    # Chào mừng ở màn hình đăng nhập
    "welcome_sign": "Chào mừng đến với trang quản trị The Sailing Bay",

    # Bản quyền ở footer
    "copyright": "The Sailing Bay Hotel Ltd.",

    # --- TÙY CHỈNH GIAO DIỆN ---
    # Theme (bạn có thể thử "flatly", "cerulean", "darkly"...)
    "theme": "flatly",

    # Tùy chỉnh menu bên (sidebar)
    "side_menu_nav": True,

    # Hiển thị model theo nhóm app
    "show_models_in_menu": True,

    # Tùy chỉnh menu (Nếu bạn muốn sắp xếp lại các app)
    "navigation_expanded": True,
    "icons": {
        "auth": "fas fa-users-cog",
        "users.User": "fas fa-user",
        "booking.Booking": "fas fa-calendar-check",
        "booking.RoomType": "fas fa-door-open",
        "booking.Room": "fas fa-bed",
        "booking.Inventory": "fas fa-clipboard-list",
        "services.Service": "fas fa-concierge-bell",
    },
}